### PR TITLE
Resized zoom.svg

### PR DESCRIPTION
**Pull request by xelser**
It was bit bigger that it's noticable. I made this a while ago and forgot to push upstream but here it is.

### CODE REVIEW

**Comment by MolassesLover** [comment]
What were all those `Updated @ fedora` commits for?

**Comment by xelser** [comment]
its my alias for my git commands.

**Comment by MolassesLover** [comment]
Sorry, I was wondering what changes you made in those commits, since I can't really tell. 

Also, it's clever to use an alias but I recommend removing automatic messages, since those actually come in really handy for managing a repository like this. No worries, though; it isn't a problem.

Thanks for your contributions! (✿◠‿◠)

**Comment by xelser** [comment]
Files that i edited where `goverlay.svg` (which i reverted back to original), `zoom.svg` and the warpinator link. That's it.

**Comment by MolassesLover** [comment]
Oh, my bad! It looked like there were an overwhelming amount of changes authored by you, but it's by Vince. 

I'm still really new to Git, sorry!

**Comment by xelser** [comment]
No worries, I don't even know jack shit about programming.

**Pull request merged**
